"ok

diff --git a/bsearch b/bsearch
--- a/bsearch
+++ b/bsearch
@@ -135,7 +135,7 @@ debug="$opt_g"
 # Option -b
 
 [ "$arg_opt_b" ] && [ ! "$arg_opt_b" = "dec" ] && [ ! "$arg_opt_b" = "hex" ] && {
-  echo "$(basename $0): The BASE argument for option -b is not valid. It must be either 'dec' or 'hex'."
+  echo "$(basename "$0"): The BASE argument for option -b is not valid. It must be either 'dec' or 'hex'."
   exit 2
 }
 
@@ -144,7 +144,7 @@ base="${arg_opt_b:-dec}"
 # Option -t
 
 [ ! "$opt_t" ] && {
-  echo "$(basename $0): Required option missing - -t NUMBER"
+  echo "$(basename "$0"): Required option missing - -t NUMBER"
   exit 2
 }
 
@@ -155,12 +155,12 @@ tgt_orig="$arg_opt_t"
 # Option -s
 
 [ ! "$opt_s" ] && {
-  echo "$(basename $0): Required option missing - -s FILE"
+  echo "$(basename "$0"): Required option missing - -s FILE"
   exit 2
 }
 
 [ ! -e "$arg_opt_s" ] && {
-  echo "$(basename $0): The file path given in search space argument FILE for option -s doesn't point to an existing file."
+  echo "$(basename "$0"): The file path given in search space argument FILE for option -s doesn't point to an existing file."
   exit 2
 }
 
@@ -170,7 +170,7 @@ len_space="$(wc -l <<< "$space")"
 # Option -e
 
 [ "$arg_opt_e" ] && [ ! "$arg_opt_e" = "lt" ] && [ ! "$arg_opt_e" = "le" ] && [ ! "$arg_opt_e" = "e" ] && [ ! "$arg_opt_e" = "ge" ] && [ ! "$arg_opt_e" = "gt" ] && {
-  echo "$(basename $0): The EQUALITY argument for option -e is not valid."
+  echo "$(basename "$0"): The EQUALITY argument for option -e is not valid."
   exit 2
 }
 
@@ -179,7 +179,7 @@ eql="${arg_opt_e:-"le"}"
 # Option -r
 
 [ "$arg_opt_r" ] && [ ! "$arg_opt_r" = "min" ] && [ ! "$arg_opt_r" = "max" ] && {
-  echo "$(basename $0): The SIZE argument for option -r is not valid."
+  echo "$(basename "$0"): The SIZE argument for option -r is not valid."
   exit 2
 }
 
@@ -215,11 +215,11 @@ Loop:${idx_loop}
 Iteration:${idx_itr}
 :"
 
-  column -t -s ':' -W 2 <<< "$state"
+  column -t -s ':' -W "2" <<< "$state"
 }
 
 at() {
-  echo "$space" | sed "$(($1 + 1))!d" # +1 for 0-indexed idx conversion to line num
+  echo "$space" | sed "$(("$1" + "1"))!d" # +1 for 0-indexed idx conversion to line num
 }
 
 found() {
@@ -230,12 +230,12 @@ found() {
 }
 
 not_found() {
-  echo "$(basename $0): No search space number in the given direction from the target number."
+  echo "$(basename "$0"): No search space number in the given direction from the target number."
   exit 1
 }
 
 search_loop() {
-  idx_loop="$(("$idx_loop" + 1))" idx_itr="0"
+  idx_loop="$(("$idx_loop" + "1"))" idx_itr="0"
   while [ "$idx_min" -lt "$idx_max" ]; do idx_itr="$(("$idx_itr" + "1"))"
     print_state
 
@@ -277,29 +277,29 @@ search_loop() {
 }
 
 [ "$eql" = "gt" ] && {
-  [ "$tgt" -ge "$(at "$(($len_space - 1))")" ] && not_found
+  [ "$tgt" -ge "$(at "$(("$len_space" - "1"))")" ] && not_found
 
   idx_min="0" idx_max="$len_space"
   f() { [ "$(at "$idx_mid")" -gt "$tgt" ] && echo "1" || echo "0"; }
   search_loop
 
   [ "$rpt" = "max" ] && {
-    idx_res="$idx_min" idx_min="$(($idx_res - 1))" idx_max="$(("$len_space" - 1))"
-    f() { [ "$(at "$(("$idx_mid" + 1))")" -ne "$(at "$idx_res")" ] && echo "1" || echo "0"; }
+    idx_res="$idx_min" idx_min="$(("$idx_res" - "1"))" idx_max="$(("$len_space" - "1"))"
+    f() { [ "$(at "$(("$idx_mid" + "1"))")" -ne "$(at "$idx_res")" ] && echo "1" || echo "0"; }
     search_loop
   }
 }
 
 [ "$eql" = "ge" ] && {
-  [ "$tgt" -gt "$(at "$(($len_space - 1))")" ] && not_found
+  [ "$tgt" -gt "$(at "$(("$len_space" - "1"))")" ] && not_found
 
   idx_min="0" idx_max="$len_space"
   f() { [ "$(at "$idx_mid")" -ge "$tgt" ] && echo "1" || echo "0"; }
   search_loop
 
   [ "$rpt" = "max" ] && {
-    idx_res="$idx_min" idx_min="$(($idx_res - 1))" idx_max="$(("$len_space" - 1))"
-    f() { [ "$(at "$(("$idx_mid" + 1))")" -ne "$(at "$idx_res")" ] && echo "1" || echo "0"; }
+    idx_res="$idx_min" idx_min="$(("$idx_res" - "1"))" idx_max="$(("$len_space" - "1"))"
+    f() { [ "$(at "$(("$idx_mid" + "1"))")" -ne "$(at "$idx_res")" ] && echo "1" || echo "0"; }
     search_loop
   }
 }
